### ISSUE TITLE
Export graphml issue with lists

### ISSUE THREAD

**Issue by FlxVctr** [neo4j-contrib/neo4j-apoc-procedures#139]
I've exported to graphml via

```
CALL apoc.export.graphml.query("MATCH p=(:User)-[m:MENTIONED]->(:User) RETURN p LIMIT 1000",'/home/ubuntu/Bowie/test.graphml',{})
```

Now, trying to open it with graph-tool I get the following error message:

```
OSError: error reading from file 'test.graphml':parse error: on line 4, column 59: unrecognized type "" for key
```

I guess for this I have to enable some option to get the types in the header of the graphml, right? Would be nice to have some details about the options in the documentation.

But here's the main issue

Line 4 reads like this:

```
<node id="n7430492" labels=":User"><data key="labels">:User</data><data key="user_id">{SOME_USER_ID}</data><data key="user_screen_name">[Ljava.lang.String;@2c8438aa</data></node>
```

So, `[Ljava.lang.String;@2c8438aa` should actually be an array of strings. Any chance to fix that?

**Comment by jexp** [comment]
We had a discussion about that before,
what would your graph tool understand as a list of values?

Comma separated? JSON list ?

On Thu, Sep 8, 2016 at 9:09 AM, Felix Victor Münch <notifications@github.com

**Comment by FlxVctr** [comment]
I'm working in Python so it'd be [item1, item2, item3]. But anything would be better than that, as long as it gives back the items with any kind of separator.

The other issue seems to stem from the fact, that using the export command above does not write the types of the attributes of the nodes to the header. Is there a config for that? (btw, this does not work reliable with the shell-tools export either, I always have to add the label types and some others by hand after exporting, but this would be another issue)

**Comment by jexp** [comment]
There is an option useTypes:true

But graphml has no type for lists. That's why they are currently skipped 
Only primitives, so we would have to indicate it somehow

Eg 
- strings
- string[]
- [string]
- ...

Any ideas?

Von meinem iPhone gesendet

**Comment by FlxVctr** [comment]
I'd define string as the type for labels (this way they'd also read correctly by gephi for example) and also go with strings for lists (in whatever readable representation, I guess JSON format is a good joice) as long as graphml does not have a list type. This way any programmer can sort it out themselves and most tools that use a GUI will give users a human readable representation.

Of course types within lists are lost this way, but from my perspective it is kind of an expected behaviour as Neo4j also defaults to string for import types.

**Comment by FlxVctr** [comment]
I would not start to introduce types outside of the graphml definition as this would definitely lead to errors when reading graphml with other tools.

**Comment by FlxVctr** [comment]
You could, but I don't expect this to scale very well, also flatten every list and then use the types inside the list, like here: https://medium.com/@amirziai/flattening-json-objects-in-python-f5343c794b10#.tg145upxe

**Comment by jexp** [comment]
Should be fixed. Please check  and close issue accordingly.

**Comment by FlxVctr** [comment]
Thanks! Export of list works now. Import, e.g. to Gephi would still fail because there's no type for the key "labels":

```xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<key id="user_id" for="node" for="node" attr.name="user_id" attr.type="string"/>
<key id="user_screen_name" for="node" for="node" attr.name="user_screen_name" attr.type="string" attr.list="string"/>
<key id="timestamp" for="edge" for="edge" attr.name="timestamp" attr.type="long"/>
<node id="n7430492" labels=":User"><data key="labels">:User</data><data key="user_id">1234567890</data><data key="user_screen_name">["some_name"]</data></node>
```

To make it work I always have to add

```xml
<key id="labels" for="node" attr.name="labels" attr.type="string"/>
<key id="label" for="edge" attr.name="label" attr.type="string"/>
```

by hand.

**Comment by FlxVctr** [comment]
Oh. Just noticed this now:

In line 4 I somehow have a doubled `for=` now.

```xml
<key id="user_id" for="node" for="node" attr.name="user_id" attr.type="string"/>
```

**Comment by jexp** [comment]
@FlxVctr should be fixed now, or?

**Comment by jexp** [comment]
pign @FlxVctr

**Comment by FlxVctr** [comment]
Yep. Still on to that. Will have to do an export this week and let you know whether it works.

**Comment by FlxVctr** [comment]
@jexp On which branch do you expect it to be fixed?

**Comment by jexp** [comment]
@FlxVctr should be on the 3.0.8.6 or 3.1.x and 3.2.x branches.

**Comment by FlxVctr** [comment]
Will check and close next time I do an export.

**Comment by AngeloBusato** [comment]
I did some tests, and this problem seems to be solved. @FlxVctr @jexp can you confirm so this issue could be closed?

**Comment by conker84** [comment]
I'm closing this as it seems to be solved. Feel free to reopen in case it comes back

**Comment by FlxVctr** [comment]
Sure, sorry for not having acted on this. Busy times and did not have a Neo4j installation running for some time, so had no possibility to test it quickly on the side.
