### ISSUE TITLE
Test suite has 4 failing tests when building on a windows system

### ISSUE THREAD

**Issue by mdfrenchman** [neo4j-contrib/neo4j-apoc-procedures#171]
3 GraphMLExport tests fail because it isn't system agnostic for line endings.

apoc.text.StringCleanTest.testClean fails as well. Not sure why yet but likely due to the differences in Windows/Unix converting the fonts.

**Comment by jexp** [comment]
@mdfrenchman is this fixed now? if so, please close this issue.

**Comment by mdfrenchman** [comment]
testClean still fails but that could just be an issue with the windows file system.  I haven't been able to build the updated JAR locally to test it out manually.

**Comment by jexp** [comment]
@mdfrenchman is this still an issue?

**Comment by mdfrenchman** [comment]
I haven’t worked on apoc in a while so can’t say for sure. If no one else has mentioned it it’s probably resolved.
